name: MacOS ARM64 Wheels

on:
  workflow_dispatch:

jobs:
  wheels-macos:
    runs-on: macos-13
    steps:
    - name: Checkout ORE-SWIG
      uses: actions/checkout@v4
    - name: get QuantLib-SWIG
      run: |
        git submodule update --init
    - name: Checkout ORE
      uses: actions/checkout@v4
      with:
          repository: OpenSourceRisk/ORE-Gitlab
          token: ${{ secrets.ORG_ACTIONS_ACCESS }}
          path: './ORE'
          submodules: true
          fetch-depth: 0
    - name: Install Eigen
      run: |
        brew install eigen
    - name: Install Swig
      run: |
        brew install swig
    - name: Install Boost
      run: |
        curl -O -L https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.gz
        tar xfz boost_1_84_0.tar.gz
        cd boost_1_84_0
        ./bootstrap.sh
        ./b2 architecture=arm address-model=64 -s NO_LZMA=1 -s NO_ZSTD=1 abi=aapcs install
    - name: Build ORE CMake
      run: |
        cd ORE
        mkdir build
        cd build
        cmake .. -DCMAKE_OSX_ARCHITECTURES=arm64 -DORE_USE_ZLIB=ON -DORE_BUILD_DOC=OFF -DORE_BUILD_EXAMPLES=OFF -DORE_BUILD_TESTS=OFF -DORE_BUILD_APP=OFF -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_ENABLE_SESSIONS=ON -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j4
        cmake --install .
    - name: Wrap ORE-SWIG
      run: |
        pwd
        python -m pip install setuptools
        cp wheels/oreanalytics-config.macos OREAnalytics-SWIG/oreanalytics-config
        cd OREAnalytics-SWIG
        ls -al
        cd SWIG
        ls -al
        chmod +x oreanalytics.i
        cd ..
        cd Python
        ls -al
        pwd
        python setup.py wrap
    - name: Build Wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        #CIBW_SKIP: cp36-*
        CIBW_BUILD: cp313-macosx*
        #CIBW_BUILD: cp311-macosx_arm64
        CIBW_ARCHS_MACOS: arm64
        CXXFLAGS: -std=c++17 -g0 -O3
        CIBW_BUILD_VERBOSITY: 2
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
          DYLD_LIBRARY_PATH=/usr/local/lib delocate-listdeps {wheel} &&
          DYLD_LIBRARY_PATH=/usr/local/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
      with:
        package-dir: ${{ github.workspace }}/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-macos-arm64
        path: ./wheelhouse/*.whl
