name: C/C++ CI Windows

on:
  push:
    tags:
       - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: building
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: x86
            platform: Win32
            boost-lib: 32
          - arch: AMD64
            platform: x64
            boost-lib: 64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.ORG_ACTIONS_ACCESS }}
    #- name: get QuantLib and QuantLib-SWIG
    #  run: |
    #    git submodule update --init --recursive
    - name: zlib
      run: |
        $Url = "https://www.zlib.net/zlib131.zip"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\zlib.zip")
        Expand-Archive -Path "$env:TEMP\zlib.zip" -DestinationPath C:\local
        cd C:\local\zlib-1.3.1
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: eigen
      run: |
        $Url = "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\eigen.zip")
        Expand-Archive -Path "$env:TEMP\eigen.zip" -DestinationPath C:\local
        cd C:\local\eigen-3.4.0
        mkdir build
        cd build
        cmake ..
    - name: Set up Boost
      run: |
        $Url = "https://archives.boost.io/release/1.80.0/binaries/boost_1_80_0-msvc-14.2-${{ matrix.boost-lib }}.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
        choco install -y ninja
    - name: cmake configure and build
      env:
        BOOST_ROOT: C:\local\boost
      shell: cmd
      run: |
        SET ORE_DIR=%cd%
        SET ORE=%cd%
        SET ZLIB_ROOT=C:\local\zlib-1.3.1
        SET Eigen3_DIR=C:\local\eigen-3.4.0
        mkdir build
        cd build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Vc\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }} -vcvars_ver=14.2 || exit 1
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DQL_BUILD_EXAMPLES=false -DQL_BUILD_TEST_SUITE=false -DQL_BUILD_BENCHMARK=false -DQL_ENABLE_SESSIONS=true -DORE_BUILD_DOC=false -DORE_BUILD_SWIG=false -DZLIB_LIBRARY=C:\local\zlib-1.3.1\build\Release\zlib.lib -DBOOST_INCLUDEDIR=C:\local\boost -DBOOST_LIBRARYDIR=C:\local\boost\lib${{ matrix.boost-lib }}-msvc-14.2 -L
        cmake --build . -j 2 --verbose
    - name: Wrap ORE-SWIG for Python Wheels
      run: |
        SET BOOST_INCLUDEDIR=C:\local\boost
        SET BOOST_LIBRARYDIR=C:\local\boost\lib${{ matrix.boost-lib }}-msvc-14.2
        SET BOOST_LIB=C:\local\boost\lib${{ matrix.boost-lib }}-msvc-14.2
        cd ${{ github.workspace }}\ORE-SWIG
        python setup.py wrap
    - name: Build ORE Wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        BOOST: C:\local\boost
        BOOST_LIB: C:\local\boost\lib${{ matrix.boost-lib }}-msvc-14.2
        ORE: ${{ github.workspace }}
        ORE_DIR: ${{ github.workspace }}
        ORE_STATIC_RUNTIME: 1
        ORE_USE_ZLIB: 1
        CIBW_SKIP: cp36-* cp37-*
        #CIBW_BUILD: cp37-win_amd64
        #CIBW_BUILD: cp38-win32
        #CIBW_BUILD: cp37-*
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
      with:
        package-dir: ${{ github.workspace }}\ORE-SWIG
    - name: Save wheels as artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: wheels-windows-${{ matrix.arch }}
        path: ./wheelhouse/*.whl