name: C/C++ CI Ubuntu

on:
  push:
    branches: [master]
  release:
   types: [published]
  pull_request:
    branches: [master]
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - .github/workflows/linux_build.yaml
      - ./App/**
      - ./OREAnalytics/**
      - '!./OREAnalytics/doc/**'
      - ./OREData/**
      - '!./OREData/doc/**'
      - ./ORETest/**
      - ./QuantExt/**
      - '!./QuantExt/doc/**'
      - CMakeLists.txt
  workflow_dispatch:

jobs:
  build:
    name: building
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Debug
      run: |
        echo ${GITHUB_WORKSPACE}
    - name: get QuantLib
      run: |
        git submodule update --init
    - name: Set up Boost
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev libboost-test-dev ninja-build
    - name: cmake configure
      run : |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                            -DBUILD_SHARED_LIBS=false \
                            -DQL_BUILD_EXAMPLES=false \
                            -DQL_BUILD_TEST_SUITE=false \
                            -DQL_BUILD_BENCHMARK=false \
                            -DQL_ENABLE_SESSIONS=true \
                            -DORE_BUILD_DOC=false \
                            -DORE_BUILD_EXAMPLES=false \
                            -DORE_BUILD_APP=true \
                            -DORE_BUILD_TESTS=true \
                            -L
    - name: cmake build
      run: cd build/; pwd; cmake --build . -j $(nproc)
    - name: Debug
      run: |
        ls ${{ github.workspace }}
    - name: Save tests artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ored-test-suite
        path: |
          ${{ github.workspace }}/build/OREData/test/ored-test-suite
          ${{ github.workspace }}/build/OREAnalytics/test/orea-test-suite
          ${{ github.workspace }}/build/QuantExt/test/quantext-test-suite
    - name: Save executables as artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: ore-exe-linux
        path: ${{ github.workspace }}/build/App/ore

# Run tests
  tests:
    name: testing
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ored-test-suite
          path: ${{ github.workspace }}/build/OREData/test/ored-test-suite
      - name: run OREData tests
        run: |
          ${{ github.workspace }}/build/OREData/test/ored-test-suite -- --base_data_path=OREData/test
